---
title: "extractr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{extractr}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(extractr) # devtools::install_local(force = T) # devtools::load_all()
```

## Get regions of interests
Load region-of-interest (RoI) geojson files.
These RoIs are used to define the area that we will extract data for.
```{r}
if (!require("librarian"))
  install.packages("librarian")

librarian::shelf(
  dplyr, here, mapview, sf)

fk_roi_sf <- read_sf("https://github.com/marinebon/extract-app/raw/main/data/fk_roi.geojson")
fk_sta_sf <- read_sf("https://github.com/marinebon/extract-app/raw/main/data/fk_sta.geojson")

fk_sf <- bind_rows(fk_roi_sf, fk_sta_sf)

mapview(fk_sf)
```

## Get ERDDAP dataset information
```{r}
ed_info <- get_ed_info("https://coastwatch.pfeg.noaa.gov/erddap/griddap/jplMURSST41mday.html")
ed_info
```

Additional ERDDAP datasets of interest:
- https://upwell.pfeg.noaa.gov/erddap/griddap/jplMURSST41mday.html
- https://coastwatch.pfeg.noaa.gov/erddap/griddap/jplMURSST41mday.html

## Extract
Extract a time-series for a given dataset and RoI
```{r}
dir_tif <- here::here("data_tmp")  # directory for storing .tif files
grds <- get_ed_grds(
  ed_info, 
  ed_var="sst",  # variable name from the ERDDAP 
  ply=fk_sf,  # polygon of the RoI
  dir_tif=dir_tif, 
  date_beg = "2021-10-01"  # start of time-series
  # date_end defaults to the current date
)
```

## Summarize the Extracted Time Series
```{r}
ts_csv <- here::here("data_tmp/ts.csv")
ts <- grds_to_ts(
  grds, fxns = c("mean", "sd"), ts_csv, verbose = T)
head(ts)
```

## Plot the Extracted Time Series
```{r}
plot_ts(ts_csv, "mean", "sd")
```
